version: "3.3"
services:
  spark-master:
    image: docker.io/bitnami/spark:3.3
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - /home/nfs/nas/docker/spark/data:/opt/spark-data
      - /home/nfs/nas/docker/spark/apps:/opt/spark-apps
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker-a:
    image: docker.io/bitnami/spark:3.3
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_LOCAL_IP=spark-worker-a
      - SPARK_WORKLOAD=worker
