---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:	
      - "/data_nas/data/media/books:/books"
      - "/data_nas/data/media/metadata:/metadata"
      - "/opt/docker/readarr/config:/config"
      - "/data_nas/data/media/downloads:/downloads" #<-- generic download folder (same for qbittorrent, lidarr, sonarr, readarr, radar)
    ports:
      - 8787:8787
    restart: unless-stopped

