version: '3.9'

networks:
  media_center:
    external: true
    name: media_center
  nginx_nginx_net:
    external: true
    name: nginx_nginx_net
  qbittorrent_default:
    external: true
    name: qbittorrent_default
  default:
    external: true
    name: media_center

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    privileged: true
    ports:
      - "9443:9443" # Use HTTPS for security
      - "9000:9000" # Optional, if you need the non-HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/portainer/data:/data
    networks:
      - media_center
      - nginx_nginx_net
      - qbittorrent_default
    restart: unless-stopped
