version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9443:9443" # Use HTTPS for security
      - "9000:9000" # Optional, if you need the non-HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/portainer/data:/data
    restart: unless-stopped
