version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/config/sites-enabled:/etc/nginx/conf.d:ro
      - /opt/docker/nginx/certs:/etc/letsencrypt
      - /opt/docker/nginx/www:/var/www/certbot
      # --- ADD THESE TWO NEW VOLUMES FOR SECUTIRY---
      - /opt/docker/nginx/config/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf:ro
      - /opt/docker/nginx/config/security-headers.conf:/etc/nginx/security-headers.conf:ro
      # (Optional but recommended for CrowdSec/Fail2Ban later)
      - /opt/docker/nginx/logs:/var/log/nginx
    networks:
      - nginx_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /opt/docker/nginx/certs:/etc/letsencrypt
      - /opt/docker/nginx/www:/var/www/certbot

networks:
  nginx_net:
    driver: bridger