services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "880:80"          # For standard HTTP
      - "8443:443"        # For standard HTTPS
      - "12345:12345"    # For your custom service if needed
    volumes:
      # Main nginx config
      - /opt/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/config/proxy.conf:/etc/nginx/proxy.conf:ro
      # Extra site or reverse proxy configs
      - /opt/docker/nginx/config/sites-enabled:/etc/nginx/conf.d:ro
      # SSL certificates (update path if different)
      - /opt/docker/nginx/config/cert/57dc2236-a6a2-48d3-acbe-e98690067859:/etc/nginx/certs:ro
      # Static files (optional)
      #- ./data:/usr/share/nginx/html:ro
      # Optional: custom logs
      #- ./data/log:/var/log/nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      # You can define env vars if you use templates - for basic configs, not always needed.
    networks:
      - nginx_net
networks:
  nginx_net:
    driver: bridge