
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/config/sites-enabled:/etc/nginx/conf.d:ro
      - /opt/docker/nginx/certs:/etc/letsencrypt
      - /opt/docker/nginx/www:/var/www/certbot
      # --- ADD THESE TWO NEW VOLUMES FOR SECUTIRY---
      - /opt/docker/nginx/config/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf:ro
      - /opt/docker/nginx/config/security-headers.conf:/etc/nginx/security-headers.conf:ro
      # (Optional but recommended for CrowdSec/Fail2Ban later)
      - /opt/docker/nginx/logs:/var/log/nginx
    networks:
      - nginx_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /opt/docker/nginx/certs:/etc/letsencrypt
      - /opt/docker/nginx/www:/var/www/certbot
      - /opt/docker/nginx/logs:/var/log/nginx:ro

  # --- ADD THE CROWDSEC AGENT ---
  crowdsec:
    image: crowdsecsecurity/crowdsec:latest
    container_name: crowdsec-agent
    restart: unless-stopped
    environment:
      # This tells CrowdSec to automatically install the nginx collection
      - COLLECTIONS=crowdsec/nginx
      # Ensure this GID matches the 'docker' group GID or your user's GID on the host
      - GID=1000
    volumes:
      # Mount the nginx logs so the agent can read them
      - /opt/docker/nginx/logs:/var/log/nginx:ro
      # Mount the local data directory
      - /opt/docker/nginx/crowdsec-data:/var/lib/crowdsec/data
      # Mount the local config directory
      - /opt/docker/nginx/crowdsec-config:/etc/crowdsec
    networks:
      - nginx_net

  # --- ADD THE NGINX BOUNCER ---
  bouncer-nginx:
    image: crowdsecsecurity/nginx-bouncer:latest
    container_name: crowdsec-bouncer
    restart: unless-stopped
    environment:
      # This API key will be generated in the next phase
      - CROWDSEC_BOUNCER_API_KEY=YOUR_API_KEY_HERE
      # This tells the bouncer how to find the agent
      - CROWDSEC_AGENT_HOST=crowdsec-agent:8080
      # Run in production mode
      - GIN_MODE=release
    depends_on:
      - crowdsec
    networks:
      - nginx_net

networks:
  nginx_net:
    driver: bridge