version: '3.9'
services:
    kavita:
        image: jvmilazz0/kavita:latest
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Brussels
        volumes:
            - "/data_nas/data/media/books:/books"
            - "/data_nas/data/media/metadata:/metadata"
            - "/opt/docker/kavita/config:/config"
        ports:
            - "5471:5000"
        restart: unless-stopped
