services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - PASSWORD=HM0nqPAamVHAw8
      - CUSTOM_USER=calibre_admin
      - CUSTOM_USER=calibre_admin
      - CLI_ARGS= #optional

      # VNC Configuration
      #- CUSTOM_PORT=8080
      #- CUSTOM_HTTPS_PORT=8181
      #- TITLE=Calibre
      ## Enable VNC access
      #- SUBFOLDER=/ 
    volumes: 
      - "/data_nas/data/media/books:/books"
      - "/opt/docker/calibre/data:/data"
      - "/opt/docker/calibre/config:/config"
    ports:
      #- "8080:8080"   # HTTP Web GUI
      #- "8081:8081"   # Content Server
      #- "8181:8181"   # HTTPS Web GUI
      #- "5900:5900"   # VNC port
      #- "6080:6080"   # noVNC (web-based VNC)
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
