networks:
  media_center:
    external: true
    name: media_center
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      # - AUTO_UPDATE=true #optional
      # - RUN_OPTS= #optional
    volumes:
      - "/opt/docker/jackett/config:/config"
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - media_center