networks:
  media_center:
    external: true
    name: media_center

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      # --- ADD THE LINES BELOW FOR ARR-SCRIPTS ---
      - RUN_SCRIPTS_ON_START=Y
      - POST_DOWNLOAD_FOLDER=/scripts/sonarr
    volumes:
      - "/opt/docker/sonarr/config:/config"
      - "/data_nas/data/media/tvseries:/tvseries"
      - "/data_nas/data/media/downloads:/downloads" #<-- generic download folder (same for qbittorrent, lidarr, sonarr, readarr, radar)
      # --- ADD THE LINE BELOW FOR ARR-SCRIPTS ---
      - "/opt/docker/arr-scripts:/scripts"
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media_center
