networks:
  media_center:
    external: true
    name: media_center

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    volumes:
      - "/opt/docker/flaresolverr/config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - media_center

